name: Build module release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install 7z
        uses: edgarrc/action-7z@v1.0.5

      - name: Get current time
        run: |
          timestamp_with_random="$(date +'%Y%m%d')"
          echo "$timestamp_with_random" > current_time.txt

      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "$LATEST_TAG" > latest_tag.txt
        
      - name: Create update.json
        run: |
          # 创建update.json
          cat > update.json << EOF
          {
            "version": "${LATEST_TAG}",
            "versionCode": "${CURRENT_TIME}",
            "zipUrl": "https://github.com/${Github_update_repo}/releases/download/${LATEST_TAG}/${action_name}_${LATEST_TAG}.zip",
            "changelog": "https://github.com/${Github_update_repo}/releases/tag/${LATEST_TAG}"
          }
          EOF
          
          mkdir bin

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Start Build
        run: |
          . module_settings/config.sh
          LATEST_TAG=$(cat latest_tag.txt)
          CURRENT_TIME=$(cat current_time.txt)
          . build_for_GITHUBACTION.sh

      - name: Compress files
        run: |
          LATEST_TAG=$(cat latest_tag.txt)
          . ./module_settings/config.sh
          7z a -r -mx9 "${action_name}_${LATEST_TAG}.zip" * -x!*.git* -x!*.zip -x!latest_tag.txt -x!current_time.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip

      - name: Update repository update.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add update.json
          git commit -m "chore: update update.json for ${LATEST_TAG}" || echo "No changes to commit"
          git push
